// <auto-generated />
using FirstApi.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FirstApi.Migrations
{
	[DbContext(typeof(PgContext))]
	[Migration("20240509234849_Initial")]
	partial class Initial
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "8.0.4")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("FirstApi.FirstModel", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("Password")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("FirstModel");
				});
#pragma warning restore 612, 618
		}
	}
}
